In [2]:
import pandas as pd
import numpy as np
from datetime import datetime

from setting_for_sdm.path_setting import path_list
from setting_for_sdm.date_setting import Date_Setting


import lib.stats.stats as st
from lib.utils.file_io import *
from lib.utils.statistics import *
from lib.utils.settings import set_matplotlib
from matplotlib import pyplot as plt

import matplotlib as mpl
import lib.visualization.plot_generator as PlotGen
import lib.visualization.font_setting as font_setting
mpl.rcParams['font.family'] = font_setting.init_font()

Helvetica /home/mghan/.fonts/Helvetica/Helvetica Oblique.ttf
Registered font name: Helvetica

In [3]:
viz_dir = f'{path_list["data_root_dir"]}/result/code_complexity/run_id_0'
option_dict = load_json(f"{viz_dir}/data/option.json")
df_1 = pd.read_parquet(f'{option_dict["save_dir"]}/data/all_complexity.parquet')
option_dict

{'run_id': 0,
 'year_range': '2020to2025',
 'data_dir': '/mnt/hdd/mghan/so_difficulty_measure/data/public_for_260105/questions/python/2020to2025',
 'save_dir': '/mnt/hdd/mghan/so_difficulty_measure/result/code_complexity/run_id_0',
 'selected_tags': 'None',
 'snapshot': 'public_for_260105'}

In [4]:
# viz_dir = f'{path_list["data_root_dir"]}/result/code_complexity/run_id_1'
# option_dict = load_json(f"{viz_dir}/data/option.json")
# df_2 = pd.read_parquet(f'{option_dict["save_dir"]}/data/all_complexity.parquet')
# df_2['Path'] = df_2['Path'].str.replace('.csv', '.py')
# option_dict

In [5]:
viz_dir = f'{path_list["data_root_dir"]}/result/code_complexity/run_id_2'
option_dict = load_json(f"{viz_dir}/data/option.json")
df_2 = pd.read_parquet(f'{option_dict["save_dir"]}/data/all_complexity.parquet')
df_2['Path'] = df_2['Path'].str.replace('.csv', '.py')
option_dict

{'run_id': 2,
 'year_range': '2020to2025',
 'data_dir': '/mnt/hdd/mghan/so_difficulty_measure/data/public_for_260105/questions/python/2020to2025',
 'save_dir': '/mnt/hdd/mghan/so_difficulty_measure/result/code_complexity/run_id_2',
 'selected_tags': 'python',
 'snapshot': 'public_for_260105'}

In [6]:
df_2

,Unnamed: 0,Path,File Name,Cognitive Complexity
0,0,472268_72881429.py,472268_72881429.csv,0
1,0,852070_75104512.py,852070_75104512.csv,0
2,0,937970_74219744.py,937970_74219744.csv,0
3,0,333452_75511647.py,333452_75511647.csv,0
4,0,787216_73775884.py,787216_73775884.csv,0
...,...,...,...,...
1032184,0,888062_70545789.py,888062_70545789.csv,0
1032185,0,807463_66662716.py,807463_66662716.csv,0
1032186,0,664694_69336971.py,664694_69336971.csv,0
1032187,0,979624_67248738.py,979624_67248738.csv,0
1032188,0,693541_77955273.py,693541_77955273.csv,0

In [7]:
df_1['id'] = df_1['Path'].apply(lambda x : x.split('_')[1].split('.')[0])
df_1[['id', 'Cognitive Complexity']] = df_1[['id', 'Cognitive Complexity']].astype(int)

In [8]:
df_2['id'] = df_2['Path'].apply(lambda x : x.split('_')[1].split('.')[0])
df_2[['id', 'Cognitive Complexity']] = df_2[['id', 'Cognitive Complexity']].astype(int)

In [13]:
tmp = pd.merge(df_1, df_2, on = 'Path')

In [15]:
tmp[tmp['Cognitive Complexity_x'] != tmp['Cognitive Complexity_y']]

,Path,File Name_x,Cognitive Complexity_x,id_x,Unnamed: 0,File Name_y,Cognitive Complexity_y,id_y
2,460564_72769436.py,460564_72769436.py,1,72769436,0,460564_72769436.csv,0,72769436
7,436715_65718304.py,436715_65718304.py,10,65718304,0,436715_65718304.csv,14,65718304
8,914126_77340573.py,914126_77340573.py,1,77340573,0,914126_77340573.csv,0,77340573
14,16914_78605204.py,16914_78605204.py,1,78605204,0,16914_78605204.csv,0,78605204
16,29976_75765136.py,29976_75765136.py,6,75765136,0,29976_75765136.csv,7,75765136
...,...,...,...,...,...,...,...,...
247725,852144_74973219.py,852144_74973219.py,3,74973219,0,852144_74973219.csv,0,74973219
247726,733_76068878.py,733_76068878.py,6,76068878,0,733_76068878.csv,5,76068878
247746,1012706_76848567.py,1012706_76848567.py,0,76848567,0,1012706_76848567.csv,2,76848567
247748,960199_72011094.py,960199_72011094.py,1,72011094,0,960199_72011094.csv,2,72011094
247750,86375_73322462.py,86375_73322462.py,1,73322462,0,86375_73322462.csv,0,73322462

In [16]:
tmp = pd.merge(df_2, df_1,  on = 'Path', how = 'left')

In [22]:
tmp['Cognitive Complexity_x'].max()

np.int64(1201)

In [24]:
tmp[tmp['Cognitive Complexity_x'] ==1201]

,Unnamed: 0,Path,File Name_x,Cognitive Complexity_x,id_x,File Name_y,Cognitive Complexity_y,id_y
660360,0,383982_79702811.py,383982_79702811.csv,1201,79702811,NaN,NaN,NaN